# Generated by Django 3.2.7 on 2021-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iam',
            name='organization',
            field=models.UUIDField(default='6181c22c57b344ea9ea3726d02a9e981', editable=False),
        ),
    ]
