# Generated by Django 3.2.7 on 2021-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iam',
            name='organization',
            field=models.UUIDField(default='ff9f4a884dd045f18276cceb08196ef2', editable=False),
        ),
    ]
