# Generated by Django 3.2.7 on 2021-09-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_iam_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iam',
            name='organization',
            field=models.UUIDField(default='102e1fda4da647d68301ab3cccc81707', editable=False),
        ),
    ]
