version: '3.7'



networks:

  application:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24



services:

  db:
    networks:
      application:
        ipv4_address: 172.11.0.10
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    networks:
      application:
        ipv4_address: 172.11.0.11
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5080:80

  server:
    networks:
      application:
        ipv4_address: 172.11.0.12
    env_file: ./server/server.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    privileged: true
    command: /usr/sbin/init
    ports:
      - 80:80
      - 443:443
      - 5081:8000
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./server/logs:/var/log/httpd
      - ./app:/api
      - ./view:/var/www/html

  node:
    networks:
      application:
        ipv4_address: 172.11.0.13
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./view:/app
