# Generated by Django 3.2.7 on 2021-09-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='iam',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rootsetting',
            name='iam',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iam_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
