# Generated by Django 3.2.7 on 2021-09-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210919_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rootsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
