# Generated by Django 3.2.7 on 2021-09-08 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='url',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
