# Generated by Django 3.2.7 on 2021-09-09 03:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210909_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, validators=[api.models.number_only]),
        ),
    ]
