# Generated by Django 3.2.7 on 2021-09-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210909_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='test',
        ),
    ]
